default_language_version:
  python: python3.12
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.16.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies: ['@commitlint/config-conventional']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: name-tests-test
    args:
    - --pytest
    exclude: ^tests/factories|^tests/types|^tests/utils|^tests/data_fixtures.py
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: pretty-format-json
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: local
  hooks:
  - id: mypy
    name: mypy
    #currently awaiting mypy 3.11 release
    # entry: pdm run mypy --enable-incomplete-feature=NewGenericSyntax
    entry: pdm run mypy
    require_serial: true
    language: system
    types: [python]
