from json import dumps

describe_commit_response = '{\n  "summary": "chore: add e2e testing",\n  "purpose": "This commit appears to add end-to-end (e2e) testing capabilities to the project and refactors some elements of the codebase to support this new functionality. It makes changes in various files to update dependencies, adjust configurations, and modify existing code, likely to integrate the new e2e tests seamlessly.",\n  "breakdown": [\n    {\n      "file_name": ".env",\n      "changes_description": "Added a new environment variable, presumably to support the new e2e testing functionality."\n    },\n    {\n      "file_name": ".gitignore",\n      "changes_description": "Updated to ignore the .env file, reflecting the new environment variable addition."\n    },\n    {\n      "file_name": "e2e/__init__.py",\n      "changes_description": "Created an empty __init__.py file to enable the e2e directory as a Python package."\n    },\n    {\n      "file_name": "e2e/describe_commit_test.py",\n      "changes_description": "Added an extensive new test file (+42 lines) to test the describe_commit functionality in an end-to-end manner."\n    },\n    {\n      "file_name": "pdm.lock",\n      "changes_description": "Updated the lock file to include changes in dependencies, notably the removal of the python-dotenv package which was likely replaced or is no longer needed."\n    },\n    {\n      "file_name": "pyproject.toml",\n      "changes_description": "Removed the python-dotenv package from dependencies and adjusted file exclusion rules."\n    },\n    {\n      "file_name": "src/commit.py",\n      "changes_description": "Updated imports and function definitions to accommodate changes in the project structure."\n    },\n    {\n      "file_name": "src/llm/base.py",\n      "changes_description": "Refactored the initialization method of the `LLMClient` class to be asynchronous, facilitating async-compatible e2e tests."\n    },\n    {\n      "file_name": "src/llm/openai_client.py",\n      "changes_description": "Significant refactoring of the OpenAIClient class for better error handling and message formatting. This includes simplifications and the removal of unnecessary logging."\n    },\n    {\n      "file_name": "src/llm/result.md",\n      "changes_description": "Removed a detailed description of a previous commit that appeared to be autogenerated, indicating a change in how commit results are documented."\n    },\n    {\n      "file_name": "src/prompts.py",\n      "changes_description": "Adjusted import statements and logging mechanisms to accommodate the new testing functionality."\n    },\n    {\n      "file_name": "src/repository.py",\n      "changes_description": "Made changes to function signatures for repository cloning and commit retrieval to simplify and enhance their usage in testing scenarios."\n    },\n    {\n      "file_name": "src/types.py",\n      "changes_description": "Updated type definitions to remove unnecessary imports and simplify type declarations."\n    },\n    {\n      "file_name": "src/utils/serialization.py",\n      "changes_description": "A minor update to the serialization function to enforce a specific order during encoding, ensuring consistent results."\n    }\n  ],\n  "programming_languages_used": [\n    "Python"\n  ],\n  "additional_notes": "This commit includes a mix of configuration updates, test additions, and code refactoring. The primary aim is to support e2e testing."\n}'
grade_commit_response = dumps(
    {
        "changes_scope": {
            "grade": 6,
            "reason": "The scope includes various deletions and minor changes; might have been better broken down.",
        },
        "code_quality": {
            "grade": 8,
            "reason": "The quality of remaining code is good and follows best practices, but removed code quality is undetermined.",
        },
        "codebase_impact": {
            "grade": 7,
            "reason": "Impact on the codebase is moderate, with significant file removals and minor improvements in remaining code.",
        },
        "coding_standards": {
            "grade": 7,
            "reason": "Mostly adheres to coding standards, but removal of multiple files needs checking against standards.",
        },
        "commit_atomicity": {
            "grade": 6,
            "reason": "The commit involves removing files and renaming some methods, which are related but should be more atomic.",
        },
        "documentation_quality": {
            "grade": 5,
            "reason": "No new documentation added. Given the changes made, additional documentation could improve context.",
        },
        "message_quality": {
            "grade": 6,
            "reason": "The commit message is generic and doesn't provide detailed information about the changes made.",
        },
        "test_quality": {
            "grade": 6,
            "reason": "Quality of removed tests seems adequate, but no new tests added for retained functionality.",
        },
        "triviality": {
            "grade": 5,
            "reason": "The changes are non-trivial as they affect e2e testing and configurations, however, lack significant new features.",
        },
    }
)
