"""Base classes for LLM clients."""

from abc import ABC, abstractmethod
from typing import Any, Generic, TypeVar

from pydantic import BaseModel

from gitmind.configuration_types import MessageDefinition, ToolDefinition

T = TypeVar("T", bound=BaseModel)
M = TypeVar("M")


class LLMClient(ABC, Generic[T]):
    """Base class for LLM clients."""

    @abstractmethod
    def __init__(self, *, config: T) -> None:  # pragma: no cover
        """Initialize the client.

        Args:
            config: The client configuration.
        """
        raise NotImplementedError("Method not implemented")

    @abstractmethod
    async def create_completions(
        self,
        *,
        messages: list[MessageDefinition],
        json_response: bool = False,
        tool: ToolDefinition | None = None,
        **kwargs: Any,
    ) -> str:  # pragma: no cover
        """Create completions.

        Args:
            messages: The messages to generate completions for.
            json_response: Whether to return the response as a JSON object.
            tool: An optional tool call.
            **kwargs: Additional completion options.

        Raises:
            LLMClientError: If an error occurs while creating completions.

        Returns:
            The completion generated by the client.
        """
        raise NotImplementedError("Method not implemented")
