name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
    - uses: actions/checkout@v5
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.12
        cache: true
    - name: Install
      run: pdm install
    - name: Build
      run: pdm build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
