name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build source dist
    runs-on: ubuntu-latest
    environment: pypi
    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.12
        cache: true
        cache-dependency-path: |
          ./pdm.lock
    - name: Install Dependencies
      run: pdm install
    - name: Build sdist
      run: pdm build -d dist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
